Pre-Release 1.3.0

diff --git a/.github/workflows/data_gather.yml b/.github/workflows/data_gather.yml
--- a/.github/workflows/data_gather.yml
+++ b/.github/workflows/data_gather.yml
@@ -1,43 +1,128 @@
+#    Rankify is an Open Source AI app made to help brawl stars players reach higher ranks.
+#    Copyright (C) 2026 WoLKaR-dev
+#
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU Affero General Public License as
+#    published by the Free Software Foundation, either version 3 of the
+#    License, or (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU Affero General Public License for more details.
+#
+#    You should have received a copy of the GNU Affero General Public License
+#    along with this program.  If not, see https://www.gnu.org/licenses/
+
 name: Data gather
 on: 
   schedule:
-    - cron: 0 */3 * * * # each 3h
+    - cron: 0 */6 * * * # each 6h
   workflow_dispatch:
 
 jobs: 
   build: 
     runs-on: ubuntu-latest
     steps:
-      - name: Gets repo data
+      #
+      # Gets the repo data. 
+      #
+      - name: Getting repo info
         uses: actions/checkout@v4
         
         with:
           ref: gather 
-          token: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Install python
+          token: ${{ secrets.GITHUB_TOKEN }} # get last repo data from gather branch
+      
+      #
+      # Install python. 
+      #
+      - name: Installing python
         uses: actions/setup-python@v5
         with: 
-          python-version : '3.10'
+          python-version : '3.10' # installing python
 
-      - name: Install dependencies 
+      #
+      # Install dependencies. 
+      #
+      - name: Installing dependencies # installing dependencies for data gathering
         run: |
-          pip install -r requirements.txt
+          pip install -r requirements.txt 
         
-      - name: Execute gather
+      #
+      # Execute gather script. 
+      #
+      - name: Executing gather # execute script
         run: python3 data_gather.py
         env: 
-          BS_API_KEY: ${{ secrets.BS_API_KEY }}
-      
-      - name: Commit & Push
+          BS_API_KEY: ${{ secrets.BS_API_KEY }} # in your repo, add BS_API_KEY secret with your brawl stars api key value
+
+      #
+      # Install Kaggle CLI
+      # 
+      - name: Installing Kaggle CLI
+        run: pip install kaggle
+
+      #
+      # Create new folder and connect to kaggle. 
+      #          
+      - name: Connecting to Kaggle
         run: |
+          mkdir -p ~/.kaggle 
+          echo "${{ secrets.KAGGLE_ACCESS_TOKEN }}" > ~/.kaggle/access_token 
+          chmod 600 ~/.kaggle/access_token
+          
+          mkdir -p kaggle_data
+          cp matches.csv kaggle_data/
+
+          echo '{"id" : "wolkar/matches"}' > kaggle_data/dataset-metadata.json
+      #
+      # Send data to Kaggle
+      #
+      - name: Sending data to Kaggle 
+        run: |
+          kaggle datasets version -p kaggle_data -m "Update matches data"
+
+      #
+      # Pulling and running notebook
+      #
+      - name: Pulling and running notebook # pull and run notebook to update data on kaggle
+        run: |
+          kaggle kernels pull wolkar/rankifyv2 -p ./.run_dir --metadata
+          kaggle kernels push -p ./.run_dir 
+          echo "Waiting for notebook to finish running..."
+          while true; do
+            STATUS=$(kaggle kernels status wolkar/rankifyv2 | awk '{print $NF}')
+            if [ "$STATUS" == "complete" ]; then break; fi
+            if [ "$STATUS" == "error" ]; then echo "Error en Kaggle"; exit 1; fi
+            sleep 20
+          done
+
+          kaggle kernels output wolkar/rankifyv2 -p ./results/
+
+      #
+      # Add JSONs and models to branch. 
+      #
+      - name: Add data to branch # add new data to branch
+        run: |
+          cp ./results/draft_model.tflite ./
+          cp ./results/brawler_mapping.json ./
+          cp ./results/map_mapping.json ./
+
+          rm -rf ./.run_dir
+          rm -rf ./kaggle_data
+          rm -rf ./results
+
           git config --global user.name "Auto Gather"
           git config --global user.email "action@github.com"
           git add . 
-          git commit -m "Data gather ended" || true
-          git push 
+          git commit -m "New data added and model trained"
+          git push
       
-      - name: Upload Gathered Data Artifact
+      #
+      # Add data to release.
+      #
+      - name: Upload Gathered Data Artifact # upload gathered data
         uses: actions/upload-artifact@v4
         with: 
           name: gathered-data
@@ -45,8 +130,14 @@ jobs:
             matches.csv
             affinity.csv
             counter.csv
-      
-      - name: Release data 
+            brawler_mapping.json
+            map_mapping.json
+            draft_model.tflite
+
+      #
+      # Release public data
+      #
+      - name: Release data # release gathered data
         uses: softprops/action-gh-release@v2
         with: 
           tag_name: latest-data
@@ -58,6 +149,9 @@ jobs:
             matches.csv
             affinity.csv
             counter.csv
+            brawler_mapping.json
+            map_mapping.json
+            draft_model.tflite
           make_latest: true
           overwrite: true
         env:
